### ISSUE TITLE
not posting

### ISSUE THREAD

**Issue by parallelsys** [matthewwall/weewx-windy#3]
My data even though it shows is uploading is not posting. My station drop off the map.
I switch back to meteobridge for the time been and see if the station comes back.

**Comment by matthewwall** [comment]
can you capture the GET requests from meteobridge then compare with the GET requests from weewx-windy?

to see the requests from weewx-windy, set debug=2 in your weewx.conf then restart weewx

**Comment by matthewwall** [comment]
please use the latest windy.py (v0.2)

there are bugs in the windy.com servers that we had to work around

**Comment by parallelsys** [comment]
Thanks for the update.

I will update soon. Do you still want me to compare?
