### ISSUE TITLE
Data not showing on Windy

### ISSUE THREAD

**Issue by TadhgMor** [matthewwall/weewx-windy#4]
I suspect the data being posted is not in a form Windy expects. Windy indicates my station is reporting but not showing any data for it. Nor is Windy showing an icon for the station which supports the bad data theory.

Is there a way this can be run from the command line to see what the data it is submitting ?

thanks
Tim

**Comment by matthewwall** [comment]
set debug=2 in weewx.conf then restart weewx.  the monitor the log file.

**Comment by TadhgMor** [comment]
I've set debug=2 and I see this..

Apr 18 15:25:24 monitor weewx[21595]: restx: Windy: url: https://stations.windy.com/pws/update/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaSI6MTAyMjg0NCwiaWF0IjoxNTU1NDc3Nzg0fQ.GaZk1vhJ0lM7kDIZV9W-an0otxCz

I dont think its supposed to look like that !

**Comment by TadhgMor** [comment]
actually thats only the api key, I cant see anything beyond it.

**Comment by matthewwall** [comment]
i think you are running an old copy of windy.py

the latest should be a GET (not a POST) with all of the parameters in the GET

**Comment by TadhgMor** [comment]
uninstalled and downloaded new version, reinstalled
diff says my windy.py is the same as the new one.

My problem was journalctl wasn't wrapping the line to my terminal so I didn't see the other data.

Now that I can see the data submitted I see...

dateutc=2019-04-18+04%3A40%3A00&dewpoint=12.4625290438&temp=28.088889228&precip=0.0&gust=1.00000248549&uv=4.0&winddir=127.180007134&pressure=1018.77222358&station=0&baromin=1026.872
24664&rh=38.1111111111&wind=0.494445674955
after the api key.

BUT I'm still not showing up on Windy.com

I notice that you have no "info" section of the data submitted, i.e.


    station - 32 bit integer; required for multiple stations; default value 0; alternative names: si, stationId
    shareOption - text one of: Open, Only Windy, Private; default value is Open
    name - text; user selected station name
    latitude - number [degrees]; required; north–south position on the Earth`s surface
    longitude - number [degrees]; required; east–west position on the Earth`s surface
    elevation - number [metres]; height above the Earth's sea level (reference geoid); alternative names: elev, elev_m, altitude
    tempheight - number [metres]; temperature sensor height above the surface; alternative names: agl_temp
    windheight - number [metres]; wind sensors height above the surface; alternative names: agl_wind

Given the statement ...

"Station record in the database is created as soon as required info params are uploaded"

Shouldnt we also have the info section ?

**Comment by matthewwall** [comment]
there is no info section for http GET, only for POST

try pasting the full url from the log into a web browser, and see what response you get from the windy servers

**Comment by matthewwall** [comment]
i think this is a bug in the windy servers.  they accept imperial units but not metric.

**Comment by matthewwall** [comment]
please try commit 131f46f

**Comment by TadhgMor** [comment]
Pasting a URL directly into a browser I get a response of SUCCESS with the old URL

trying new commit now

**Comment by TadhgMor** [comment]
that fixed it ! - they have a metric problem :(

**Comment by matthewwall** [comment]
and there seem to be even more problems with their POST implementation.  too bad, because GET is not the right way to do this.  have they learned nothing from all the years of lousy WU behavior?

oh well, at least something works.

**Comment by TadhgMor** [comment]
I'll close this thread for now, and post comments on the Windy forum to see if I get a response to POST & Metric not working.
Thanks for your efforts, at least I'm showing up in the stations map now :)
