### ISSUE TITLE
v0.3 does not accept station ID and breaks SDR

### ISSUE THREAD

**Issue by gary-hammer** [matthewwall/weewx-windy#9]
I installed windy 0.3 and found that it did not like station ID and also caused my SDR driver to fail.
I commented out the Windy stanza, still had no SDR
Uninstall windy, SDR working again.
[sdr-error.txt](https://github.com/matthewwall/weewx-windy/files/3108309/sdr-error.txt)
[windy-error.txt](https://github.com/matthewwall/weewx-windy/files/3108310/windy-error.txt)

**Comment by TadhgMor** [comment]
Don't use the Windy issued station ID for the station ID here.
The Station ID should be 0

The station ID in this context is which station you are reporting from i.e. if you have 3 weather stations, your station ID's would be 0, 1, & 2

The failure of your SDR driver might just be a side affect of this module failure.

Change your ID to 0 and re-run to see if everything is OK

**Comment by TadhgMor** [comment]
Note to dev team...
Please update instructions to remove the Station ID confusion.

**Comment by matthewwall** [comment]
fixed at commit 3a7a393
